#!/usr/bin/env bash
# This script is displaying "good luck,bad luck and Best School"
n=0

while [ $n -le 9 ]
do
    if [[ "$n" == 3 ]]; then
        echo "bad luck"
    elif [[ "$n" == 7 ]]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((n++))
done
